### ISSUE TITLE
meta: dealing with language diffenrces between C++ and nim

### ISSUE THREAD

**Issue by haxscramper** [haxscramper/hcparse#18]
- [ ] nim does not have type-level immutability annotations, and instead relies on mutability of the symbols. You can't have immutable *field*, only immutable variable.
- [ ] #1 and #2 very hard to properly interface with Cxx classes. Large number of workarounds can be implemented, but all of them have limitations
- [ ] #3 full explanation in linked issue. It might be possible to provide some form of simplified workaround that shifts responsibility to the end user. It might be the only way of reliably solving this.

Todo: link related issues from other repositories

**Comment by haxscramper** [comment]
Const is a huge PITA - I dynlib deals with the inconsistencies by generating code like 

```c
typedef N_CDECL_PTR(NCSTRING, tyProc__cTCodr69cPNr9chtH7apXJYg) (NCSTRING s);
Dl_4294968796_ = (tyProc__cTCodr69cPNr9chtH7apXJYg) nimGetProcAddr(TM__xDZurH9b9cD5SoY3HyXHwqcw_2, "wave_unescapeIncludeToken");
```

and then calling it, but if I try to do a simple `importc` it seems that I either have to `header:` the procedure import, or make sure the header is never imported, otherwise I get a conflicting types error.

**Comment by haxscramper** [comment]
```nim
const
  h = "lib.h"
  l = "liblib.so"

type
  str {.importc: "struct str", header: h.} = object
    field: cint

echo str()

proc get_cstring_dl(str: cstring) {.dynlib: l, importc: "get_cstring_dl".}

get_cstring_dl(nil)

proc get_cstring_link(str: cstring) {.cdecl, importc: "get_cstring_link".}

get_cstring_link(nil)
```

```lua
target("lib")
    set_kind("shared")
    add_files("lib.c")
    set_targetdir(os.scriptdir())

target("main")
    set_kind("binary")
    add_deps("lib")
    add_files("nim_cxx_const_main.nim")
    add_links("lib")
    set_targetdir(os.scriptdir())
```

```c
void get_cstring(const char* cstring) {}
void get_cstring_link(const char* cstring) {}
```

```c
struct str {
    int field;
};

void get_cstring_dl(const char* cstring);
void get_cstring_link(const char* cstring);
```

**Comment by haxscramper** [comment]
I think this could've been trivially solved if `Static[T] {.importc: "const '0".}` worked correctly.

**Comment by haxscramper** [comment]
I can wrap each type twice - as a regular object and as a `const`. This approach is of course insane, since I can also have `ptr T`, `ptr ptr T`, `ref T` and so on, but this way nim would generate correct procedure prototypes.
