### ISSUE TITLE
Todo checklist

### ISSUE THREAD

**Issue by haxscramper** [haxscramper/hcparse#6]
- [x] Write own renderer for the AST, `compiler/renderer` is just painful to look at
- [ ] Fix missing documentation comments for `boost::wave`-expanded source code
- [x] Clean current implementation of the libclang wrappers - they still have large chunks of v1 IR implementation which are no longer necessary.
- [x] #22 
- [x] Align enum values
- [ ] Try wrapping `std::unique_ptr` and see whether there are some additional workarounds for https://github.com/haxscramper/hcparse/issues/13
